// <auto-generated />
namespace Coursmanager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class create20191216 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create20191216));
        
        string IMigrationMetadata.Id
        {
            get { return "201912160330157_create20191216"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
